### ISSUE TITLE
Erd relaties aangepast?

### ISSUE THREAD

**Issue by goldo63** [kevinvgils/PatheAppP3#28]

**Comment by ThijsRaaijmakers** [comment]
ERD is aangepast en bijgewerkt in Functioneel Ontwerp

**Comment by ThijsRaaijmakers** [comment]
ERD relaties zijn omgedraaid

**Comment by ThijsRaaijmakers** [comment]
Verplichtingen zijn toegevoegd. Dit zou (in theorie) de final version moeten zijn
